/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) omnihex_ode_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* omnihex_ode_constr_h_fun:(i0[19],i1[6],i2[],i3[])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][5]=a0;
  a0=-3.3333333333333331e-01;
  a1=arg[0]? arg[0][13] : 0;
  a0=(a0*a1);
  a2=-1.6778523489932887e-01;
  a3=arg[0]? arg[0][16] : 0;
  a4=(a2*a3);
  a0=(a0+a4);
  a4=4.7539149888143178e-01;
  a5=arg[0]? arg[0][18] : 0;
  a6=(a4*a5);
  a0=(a0+a6);
  a0=casadi_sq(a0);
  a6=-1.6666666666666666e-01;
  a7=arg[0]? arg[0][15] : 0;
  a8=(a6*a7);
  a9=-9.5078299776286357e-01;
  a9=(a9*a3);
  a8=(a8+a9);
  a9=-8.3892617449664433e-02;
  a10=(a9*a5);
  a8=(a8+a10);
  a8=casadi_sq(a8);
  a0=(a0+a8);
  a0=sqrt(a0);
  if (res[0]!=0) res[0][6]=a0;
  a0=3.3333333333333331e-01;
  a0=(a0*a1);
  a2=(a2*a3);
  a0=(a0+a2);
  a2=(a4*a5);
  a0=(a0+a2);
  a0=casadi_sq(a0);
  a2=(a6*a7);
  a8=9.5078299776286357e-01;
  a8=(a8*a3);
  a2=(a2+a8);
  a8=8.3892617449664433e-02;
  a10=(a8*a5);
  a2=(a2+a10);
  a2=casadi_sq(a2);
  a0=(a0+a2);
  a0=sqrt(a0);
  if (res[0]!=0) res[0][7]=a0;
  a0=1.6666666666666666e-01;
  a2=(a0*a1);
  a10=2.8867505551443373e-01;
  a11=arg[0]? arg[0][14] : 0;
  a12=(a10*a11);
  a2=(a2+a12);
  a12=(a8*a3);
  a2=(a2+a12);
  a12=1.4530629312147189e-01;
  a13=arg[0]? arg[0][17] : 0;
  a14=(a12*a13);
  a2=(a2+a14);
  a14=(a4*a5);
  a2=(a2+a14);
  a2=casadi_sq(a2);
  a14=(a6*a7);
  a15=(a4*a3);
  a14=(a14+a15);
  a15=8.2340195016251350e-01;
  a16=(a15*a13);
  a14=(a14+a16);
  a16=(a9*a5);
  a14=(a14+a16);
  a14=casadi_sq(a14);
  a2=(a2+a14);
  a2=sqrt(a2);
  if (res[0]!=0) res[0][8]=a2;
  a2=(a6*a1);
  a14=-2.8867505551443373e-01;
  a16=(a14*a11);
  a2=(a2+a16);
  a16=(a8*a3);
  a2=(a2+a16);
  a12=(a12*a13);
  a2=(a2+a12);
  a12=(a4*a5);
  a2=(a2+a12);
  a2=casadi_sq(a2);
  a12=(a6*a7);
  a16=-4.7539149888143178e-01;
  a17=(a16*a3);
  a12=(a12+a17);
  a17=-8.2340195016251350e-01;
  a18=(a17*a13);
  a12=(a12+a18);
  a18=(a8*a5);
  a12=(a12+a18);
  a12=casadi_sq(a12);
  a2=(a2+a12);
  a2=sqrt(a2);
  if (res[0]!=0) res[0][9]=a2;
  a2=(a6*a1);
  a10=(a10*a11);
  a2=(a2+a10);
  a10=(a8*a3);
  a2=(a2+a10);
  a10=-1.4530629312147189e-01;
  a12=(a10*a13);
  a2=(a2+a12);
  a12=(a4*a5);
  a2=(a2+a12);
  a2=casadi_sq(a2);
  a12=(a6*a7);
  a16=(a16*a3);
  a12=(a12+a16);
  a15=(a15*a13);
  a12=(a12+a15);
  a15=(a8*a5);
  a12=(a12+a15);
  a12=casadi_sq(a12);
  a2=(a2+a12);
  a2=sqrt(a2);
  if (res[0]!=0) res[0][10]=a2;
  a0=(a0*a1);
  a14=(a14*a11);
  a0=(a0+a14);
  a8=(a8*a3);
  a0=(a0+a8);
  a10=(a10*a13);
  a0=(a0+a10);
  a10=(a4*a5);
  a0=(a0+a10);
  a0=casadi_sq(a0);
  a6=(a6*a7);
  a4=(a4*a3);
  a6=(a6+a4);
  a17=(a17*a13);
  a6=(a6+a17);
  a9=(a9*a5);
  a6=(a6+a9);
  a6=casadi_sq(a6);
  a0=(a0+a6);
  a0=sqrt(a0);
  if (res[0]!=0) res[0][11]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int omnihex_ode_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int omnihex_ode_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int omnihex_ode_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void omnihex_ode_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int omnihex_ode_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void omnihex_ode_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void omnihex_ode_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void omnihex_ode_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int omnihex_ode_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int omnihex_ode_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real omnihex_ode_constr_h_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* omnihex_ode_constr_h_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* omnihex_ode_constr_h_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* omnihex_ode_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* omnihex_ode_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int omnihex_ode_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
