/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) GemCarModel_Bspline_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[35] = {3, 8, 0, 3, 6, 9, 12, 15, 18, 21, 24, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};

/* GemCarModel_Bspline_expl_vde_forw:(i0[3],i1[3x3],i2[3x8],i3[8],i4[3])->(o0[3],o1[3x3],o2[3x8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][2] : 0;
  a1=cos(a0);
  a2=3.;
  a3=arg[4]? arg[4][0] : 0;
  a4=arg[4]? arg[4][1] : 0;
  a5=(a3-a4);
  a5=(a2*a5);
  a6=arg[4]? arg[4][2] : 0;
  a7=(a4-a6);
  a5=(a5/a7);
  a7=(a3-a4);
  a7=casadi_sq(a7);
  a7=(a2*a7);
  a8=(a4-a6);
  a8=casadi_sq(a8);
  a7=(a7/a8);
  a5=(a5+a7);
  a7=(a3-a4);
  a8=casadi_sq(a7);
  a7=(a7*a8);
  a8=(a4-a6);
  a9=casadi_sq(a8);
  a8=(a8*a9);
  a7=(a7/a8);
  a5=(a5+a7);
  a7=1.;
  a5=(a5+a7);
  a1=(a1*a5);
  a7=arg[3]? arg[3][0] : 0;
  a8=(a1*a7);
  a9=cos(a0);
  a10=(a3-a4);
  a10=(a2*a10);
  a11=(a4-a6);
  a10=(a10/a11);
  a11=6.;
  a12=(a3-a4);
  a12=casadi_sq(a12);
  a11=(a11*a12);
  a12=(a4-a6);
  a12=casadi_sq(a12);
  a11=(a11/a12);
  a10=(a10+a11);
  a11=(a3-a4);
  a12=casadi_sq(a11);
  a11=(a11*a12);
  a11=(a2*a11);
  a12=(a4-a6);
  a13=casadi_sq(a12);
  a12=(a12*a13);
  a11=(a11/a12);
  a10=(a10+a11);
  a9=(a9*a10);
  a11=arg[3]? arg[3][2] : 0;
  a12=(a9*a11);
  a8=(a8-a12);
  a12=cos(a0);
  a13=(a3-a4);
  a13=casadi_sq(a13);
  a13=(a2*a13);
  a14=(a4-a6);
  a14=casadi_sq(a14);
  a13=(a13/a14);
  a14=(a3-a4);
  a15=casadi_sq(a14);
  a14=(a14*a15);
  a2=(a2*a14);
  a14=(a4-a6);
  a15=casadi_sq(a14);
  a14=(a14*a15);
  a2=(a2/a14);
  a13=(a13+a2);
  a12=(a12*a13);
  a2=arg[3]? arg[3][4] : 0;
  a14=(a12*a2);
  a8=(a8+a14);
  a14=cos(a0);
  a3=(a3-a4);
  a15=casadi_sq(a3);
  a3=(a3*a15);
  a4=(a4-a6);
  a6=casadi_sq(a4);
  a4=(a4*a6);
  a3=(a3/a4);
  a14=(a14*a3);
  a4=arg[3]? arg[3][6] : 0;
  a6=(a14*a4);
  a8=(a8-a6);
  if (res[0]!=0) res[0][0]=a8;
  a8=sin(a0);
  a8=(a8*a5);
  a6=(a8*a7);
  a15=sin(a0);
  a15=(a15*a10);
  a16=(a15*a11);
  a6=(a6-a16);
  a16=sin(a0);
  a16=(a16*a13);
  a17=(a16*a2);
  a6=(a6+a17);
  a17=sin(a0);
  a17=(a17*a3);
  a18=(a17*a4);
  a6=(a6-a18);
  if (res[0]!=0) res[0][1]=a6;
  a6=arg[3]? arg[3][1] : 0;
  a6=(a5*a6);
  a18=arg[3]? arg[3][3] : 0;
  a18=(a10*a18);
  a6=(a6-a18);
  a18=arg[3]? arg[3][5] : 0;
  a18=(a13*a18);
  a6=(a6+a18);
  a18=arg[3]? arg[3][7] : 0;
  a18=(a3*a18);
  a6=(a6-a18);
  if (res[0]!=0) res[0][2]=a6;
  a6=sin(a0);
  a18=arg[1]? arg[1][2] : 0;
  a19=(a6*a18);
  a19=(a10*a19);
  a19=(a11*a19);
  a20=sin(a0);
  a21=(a20*a18);
  a21=(a5*a21);
  a21=(a7*a21);
  a19=(a19-a21);
  a21=sin(a0);
  a22=(a21*a18);
  a22=(a13*a22);
  a22=(a2*a22);
  a19=(a19-a22);
  a22=sin(a0);
  a23=(a22*a18);
  a23=(a3*a23);
  a23=(a4*a23);
  a19=(a19+a23);
  if (res[1]!=0) res[1][0]=a19;
  a19=cos(a0);
  a23=(a19*a18);
  a23=(a5*a23);
  a23=(a7*a23);
  a24=cos(a0);
  a25=(a24*a18);
  a25=(a10*a25);
  a25=(a11*a25);
  a23=(a23-a25);
  a25=cos(a0);
  a26=(a25*a18);
  a26=(a13*a26);
  a26=(a2*a26);
  a23=(a23+a26);
  a26=cos(a0);
  a18=(a26*a18);
  a18=(a3*a18);
  a18=(a4*a18);
  a23=(a23-a18);
  if (res[1]!=0) res[1][1]=a23;
  a23=0.;
  if (res[1]!=0) res[1][2]=a23;
  a18=arg[1]? arg[1][5] : 0;
  a27=(a6*a18);
  a27=(a10*a27);
  a27=(a11*a27);
  a28=(a20*a18);
  a28=(a5*a28);
  a28=(a7*a28);
  a27=(a27-a28);
  a28=(a21*a18);
  a28=(a13*a28);
  a28=(a2*a28);
  a27=(a27-a28);
  a28=(a22*a18);
  a28=(a3*a28);
  a28=(a4*a28);
  a27=(a27+a28);
  if (res[1]!=0) res[1][3]=a27;
  a27=(a19*a18);
  a27=(a5*a27);
  a27=(a7*a27);
  a28=(a24*a18);
  a28=(a10*a28);
  a28=(a11*a28);
  a27=(a27-a28);
  a28=(a25*a18);
  a28=(a13*a28);
  a28=(a2*a28);
  a27=(a27+a28);
  a18=(a26*a18);
  a18=(a3*a18);
  a18=(a4*a18);
  a27=(a27-a18);
  if (res[1]!=0) res[1][4]=a27;
  if (res[1]!=0) res[1][5]=a23;
  a27=arg[1]? arg[1][8] : 0;
  a6=(a6*a27);
  a6=(a10*a6);
  a6=(a11*a6);
  a20=(a20*a27);
  a20=(a5*a20);
  a20=(a7*a20);
  a6=(a6-a20);
  a21=(a21*a27);
  a21=(a13*a21);
  a21=(a2*a21);
  a6=(a6-a21);
  a22=(a22*a27);
  a22=(a3*a22);
  a22=(a4*a22);
  a6=(a6+a22);
  if (res[1]!=0) res[1][6]=a6;
  a19=(a19*a27);
  a19=(a5*a19);
  a19=(a7*a19);
  a24=(a24*a27);
  a24=(a10*a24);
  a24=(a11*a24);
  a19=(a19-a24);
  a25=(a25*a27);
  a25=(a13*a25);
  a25=(a2*a25);
  a19=(a19+a25);
  a26=(a26*a27);
  a26=(a3*a26);
  a26=(a4*a26);
  a19=(a19-a26);
  if (res[1]!=0) res[1][7]=a19;
  if (res[1]!=0) res[1][8]=a23;
  a19=sin(a0);
  a26=arg[2]? arg[2][2] : 0;
  a27=(a19*a26);
  a27=(a10*a27);
  a27=(a11*a27);
  a25=sin(a0);
  a24=(a25*a26);
  a24=(a5*a24);
  a24=(a7*a24);
  a27=(a27-a24);
  a24=sin(a0);
  a6=(a24*a26);
  a6=(a13*a6);
  a6=(a2*a6);
  a27=(a27-a6);
  a6=sin(a0);
  a22=(a6*a26);
  a22=(a3*a22);
  a22=(a4*a22);
  a27=(a27+a22);
  a1=(a1+a27);
  if (res[2]!=0) res[2][0]=a1;
  a1=cos(a0);
  a27=(a1*a26);
  a27=(a5*a27);
  a27=(a7*a27);
  a22=cos(a0);
  a21=(a22*a26);
  a21=(a10*a21);
  a21=(a11*a21);
  a27=(a27-a21);
  a21=cos(a0);
  a20=(a21*a26);
  a20=(a13*a20);
  a20=(a2*a20);
  a27=(a27+a20);
  a0=cos(a0);
  a26=(a0*a26);
  a26=(a3*a26);
  a26=(a4*a26);
  a27=(a27-a26);
  a8=(a8+a27);
  if (res[2]!=0) res[2][1]=a8;
  if (res[2]!=0) res[2][2]=a23;
  a8=arg[2]? arg[2][5] : 0;
  a27=(a19*a8);
  a27=(a10*a27);
  a27=(a11*a27);
  a26=(a25*a8);
  a26=(a5*a26);
  a26=(a7*a26);
  a27=(a27-a26);
  a26=(a24*a8);
  a26=(a13*a26);
  a26=(a2*a26);
  a27=(a27-a26);
  a26=(a6*a8);
  a26=(a3*a26);
  a26=(a4*a26);
  a27=(a27+a26);
  if (res[2]!=0) res[2][3]=a27;
  a27=(a1*a8);
  a27=(a5*a27);
  a27=(a7*a27);
  a26=(a22*a8);
  a26=(a10*a26);
  a26=(a11*a26);
  a27=(a27-a26);
  a26=(a21*a8);
  a26=(a13*a26);
  a26=(a2*a26);
  a27=(a27+a26);
  a8=(a0*a8);
  a8=(a3*a8);
  a8=(a4*a8);
  a27=(a27-a8);
  if (res[2]!=0) res[2][4]=a27;
  if (res[2]!=0) res[2][5]=a5;
  a27=arg[2]? arg[2][8] : 0;
  a8=(a19*a27);
  a8=(a10*a8);
  a8=(a11*a8);
  a26=(a25*a27);
  a26=(a5*a26);
  a26=(a7*a26);
  a8=(a8-a26);
  a26=(a24*a27);
  a26=(a13*a26);
  a26=(a2*a26);
  a8=(a8-a26);
  a26=(a6*a27);
  a26=(a3*a26);
  a26=(a4*a26);
  a8=(a8+a26);
  a8=(a8-a9);
  if (res[2]!=0) res[2][6]=a8;
  a8=(a1*a27);
  a8=(a5*a8);
  a8=(a7*a8);
  a9=(a22*a27);
  a9=(a10*a9);
  a9=(a11*a9);
  a8=(a8-a9);
  a9=(a21*a27);
  a9=(a13*a9);
  a9=(a2*a9);
  a8=(a8+a9);
  a27=(a0*a27);
  a27=(a3*a27);
  a27=(a4*a27);
  a8=(a8-a27);
  a8=(a8-a15);
  if (res[2]!=0) res[2][7]=a8;
  if (res[2]!=0) res[2][8]=a23;
  a8=arg[2]? arg[2][11] : 0;
  a15=(a19*a8);
  a15=(a10*a15);
  a15=(a11*a15);
  a27=(a25*a8);
  a27=(a5*a27);
  a27=(a7*a27);
  a15=(a15-a27);
  a27=(a24*a8);
  a27=(a13*a27);
  a27=(a2*a27);
  a15=(a15-a27);
  a27=(a6*a8);
  a27=(a3*a27);
  a27=(a4*a27);
  a15=(a15+a27);
  if (res[2]!=0) res[2][9]=a15;
  a15=(a1*a8);
  a15=(a5*a15);
  a15=(a7*a15);
  a27=(a22*a8);
  a27=(a10*a27);
  a27=(a11*a27);
  a15=(a15-a27);
  a27=(a21*a8);
  a27=(a13*a27);
  a27=(a2*a27);
  a15=(a15+a27);
  a8=(a0*a8);
  a8=(a3*a8);
  a8=(a4*a8);
  a15=(a15-a8);
  if (res[2]!=0) res[2][10]=a15;
  a15=(-a10);
  if (res[2]!=0) res[2][11]=a15;
  a15=arg[2]? arg[2][14] : 0;
  a8=(a19*a15);
  a8=(a10*a8);
  a8=(a11*a8);
  a27=(a25*a15);
  a27=(a5*a27);
  a27=(a7*a27);
  a8=(a8-a27);
  a27=(a24*a15);
  a27=(a13*a27);
  a27=(a2*a27);
  a8=(a8-a27);
  a27=(a6*a15);
  a27=(a3*a27);
  a27=(a4*a27);
  a8=(a8+a27);
  a12=(a12+a8);
  if (res[2]!=0) res[2][12]=a12;
  a12=(a1*a15);
  a12=(a5*a12);
  a12=(a7*a12);
  a8=(a22*a15);
  a8=(a10*a8);
  a8=(a11*a8);
  a12=(a12-a8);
  a8=(a21*a15);
  a8=(a13*a8);
  a8=(a2*a8);
  a12=(a12+a8);
  a15=(a0*a15);
  a15=(a3*a15);
  a15=(a4*a15);
  a12=(a12-a15);
  a16=(a16+a12);
  if (res[2]!=0) res[2][13]=a16;
  if (res[2]!=0) res[2][14]=a23;
  a16=arg[2]? arg[2][17] : 0;
  a12=(a19*a16);
  a12=(a10*a12);
  a12=(a11*a12);
  a15=(a25*a16);
  a15=(a5*a15);
  a15=(a7*a15);
  a12=(a12-a15);
  a15=(a24*a16);
  a15=(a13*a15);
  a15=(a2*a15);
  a12=(a12-a15);
  a15=(a6*a16);
  a15=(a3*a15);
  a15=(a4*a15);
  a12=(a12+a15);
  if (res[2]!=0) res[2][15]=a12;
  a12=(a1*a16);
  a12=(a5*a12);
  a12=(a7*a12);
  a15=(a22*a16);
  a15=(a10*a15);
  a15=(a11*a15);
  a12=(a12-a15);
  a15=(a21*a16);
  a15=(a13*a15);
  a15=(a2*a15);
  a12=(a12+a15);
  a16=(a0*a16);
  a16=(a3*a16);
  a16=(a4*a16);
  a12=(a12-a16);
  if (res[2]!=0) res[2][16]=a12;
  if (res[2]!=0) res[2][17]=a13;
  a12=arg[2]? arg[2][20] : 0;
  a16=(a19*a12);
  a16=(a10*a16);
  a16=(a11*a16);
  a15=(a25*a12);
  a15=(a5*a15);
  a15=(a7*a15);
  a16=(a16-a15);
  a15=(a24*a12);
  a15=(a13*a15);
  a15=(a2*a15);
  a16=(a16-a15);
  a15=(a6*a12);
  a15=(a3*a15);
  a15=(a4*a15);
  a16=(a16+a15);
  a16=(a16-a14);
  if (res[2]!=0) res[2][18]=a16;
  a16=(a1*a12);
  a16=(a5*a16);
  a16=(a7*a16);
  a14=(a22*a12);
  a14=(a10*a14);
  a14=(a11*a14);
  a16=(a16-a14);
  a14=(a21*a12);
  a14=(a13*a14);
  a14=(a2*a14);
  a16=(a16+a14);
  a12=(a0*a12);
  a12=(a3*a12);
  a12=(a4*a12);
  a16=(a16-a12);
  a16=(a16-a17);
  if (res[2]!=0) res[2][19]=a16;
  if (res[2]!=0) res[2][20]=a23;
  a23=arg[2]? arg[2][23] : 0;
  a19=(a19*a23);
  a19=(a10*a19);
  a19=(a11*a19);
  a25=(a25*a23);
  a25=(a5*a25);
  a25=(a7*a25);
  a19=(a19-a25);
  a24=(a24*a23);
  a24=(a13*a24);
  a24=(a2*a24);
  a19=(a19-a24);
  a6=(a6*a23);
  a6=(a3*a6);
  a6=(a4*a6);
  a19=(a19+a6);
  if (res[2]!=0) res[2][21]=a19;
  a1=(a1*a23);
  a5=(a5*a1);
  a7=(a7*a5);
  a22=(a22*a23);
  a10=(a10*a22);
  a11=(a11*a10);
  a7=(a7-a11);
  a21=(a21*a23);
  a13=(a13*a21);
  a2=(a2*a13);
  a7=(a7+a2);
  a0=(a0*a23);
  a0=(a3*a0);
  a4=(a4*a0);
  a7=(a7-a4);
  if (res[2]!=0) res[2][22]=a7;
  a3=(-a3);
  if (res[2]!=0) res[2][23]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GemCarModel_Bspline_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int GemCarModel_Bspline_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real GemCarModel_Bspline_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GemCarModel_Bspline_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GemCarModel_Bspline_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GemCarModel_Bspline_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GemCarModel_Bspline_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
