/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s2[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[51] = {11, 16, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 0, 1, 0, 1, 0, 1, 0, 1, 2, 3, 2, 3, 2, 3, 2, 3, 4, 5, 4, 5, 4, 5, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7};
static const casadi_int casadi_s5[14] = {11, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s6[3] = {16, 0, 0};

/* GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess:(i0[3],i1[8],i2[16],i3[],i4[3])->(o0[16],o1[11x16,32nz],o2[11x11,0nz],o3[16x0],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=2.;
  a1=arg[1]? arg[1][0] : 0;
  a2=(a0*a1);
  a3=3.;
  a2=(a2+a3);
  a4=arg[1]? arg[1][1] : 0;
  a5=(a0*a4);
  a5=(a5+a3);
  a2=(a2-a5);
  if (res[0]!=0) res[0][0]=a2;
  a2=-2.;
  a5=(a2*a1);
  a5=(a5+a3);
  a6=(a2*a4);
  a6=(a6+a3);
  a5=(a5-a6);
  if (res[0]!=0) res[0][1]=a5;
  a5=(a2*a4);
  a5=(a5-a3);
  a6=(a2*a1);
  a6=(a6-a3);
  a5=(a5-a6);
  if (res[0]!=0) res[0][2]=a5;
  a4=(a0*a4);
  a4=(a4-a3);
  a1=(a0*a1);
  a1=(a1-a3);
  a4=(a4-a1);
  if (res[0]!=0) res[0][3]=a4;
  a4=arg[1]? arg[1][2] : 0;
  a1=(a0*a4);
  a1=(a1+a3);
  a5=arg[1]? arg[1][3] : 0;
  a6=(a0*a5);
  a6=(a6+a3);
  a1=(a1-a6);
  if (res[0]!=0) res[0][4]=a1;
  a1=(a2*a4);
  a1=(a1+a3);
  a6=(a2*a5);
  a6=(a6+a3);
  a1=(a1-a6);
  if (res[0]!=0) res[0][5]=a1;
  a1=(a2*a5);
  a1=(a1-a3);
  a6=(a2*a4);
  a6=(a6-a3);
  a1=(a1-a6);
  if (res[0]!=0) res[0][6]=a1;
  a5=(a0*a5);
  a5=(a5-a3);
  a4=(a0*a4);
  a4=(a4-a3);
  a5=(a5-a4);
  if (res[0]!=0) res[0][7]=a5;
  a5=arg[1]? arg[1][4] : 0;
  a4=(a0*a5);
  a4=(a4+a3);
  a1=arg[1]? arg[1][5] : 0;
  a6=(a0*a1);
  a6=(a6+a3);
  a4=(a4-a6);
  if (res[0]!=0) res[0][8]=a4;
  a4=(a2*a5);
  a4=(a4+a3);
  a6=(a2*a1);
  a6=(a6+a3);
  a4=(a4-a6);
  if (res[0]!=0) res[0][9]=a4;
  a4=(a2*a1);
  a4=(a4-a3);
  a6=(a2*a5);
  a6=(a6-a3);
  a4=(a4-a6);
  if (res[0]!=0) res[0][10]=a4;
  a1=(a0*a1);
  a1=(a1-a3);
  a5=(a0*a5);
  a5=(a5-a3);
  a1=(a1-a5);
  if (res[0]!=0) res[0][11]=a1;
  a1=arg[1]? arg[1][6] : 0;
  a5=(a0*a1);
  a5=(a5+a3);
  a4=arg[1]? arg[1][7] : 0;
  a6=(a0*a4);
  a6=(a6+a3);
  a5=(a5-a6);
  if (res[0]!=0) res[0][12]=a5;
  a5=(a2*a1);
  a5=(a5+a3);
  a6=(a2*a4);
  a6=(a6+a3);
  a5=(a5-a6);
  if (res[0]!=0) res[0][13]=a5;
  a5=(a2*a4);
  a5=(a5-a3);
  a6=(a2*a1);
  a6=(a6-a3);
  a5=(a5-a6);
  if (res[0]!=0) res[0][14]=a5;
  a4=(a0*a4);
  a4=(a4-a3);
  a1=(a0*a1);
  a1=(a1-a3);
  a4=(a4-a1);
  if (res[0]!=0) res[0][15]=a4;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a2;
  if (res[1]!=0) res[1][2]=a2;
  if (res[1]!=0) res[1][3]=a0;
  if (res[1]!=0) res[1][4]=a0;
  if (res[1]!=0) res[1][5]=a2;
  if (res[1]!=0) res[1][6]=a2;
  if (res[1]!=0) res[1][7]=a0;
  if (res[1]!=0) res[1][8]=a0;
  if (res[1]!=0) res[1][9]=a2;
  if (res[1]!=0) res[1][10]=a2;
  if (res[1]!=0) res[1][11]=a0;
  if (res[1]!=0) res[1][12]=a0;
  if (res[1]!=0) res[1][13]=a2;
  if (res[1]!=0) res[1][14]=a2;
  if (res[1]!=0) res[1][15]=a0;
  if (res[1]!=0) res[1][16]=a0;
  if (res[1]!=0) res[1][17]=a2;
  if (res[1]!=0) res[1][18]=a2;
  if (res[1]!=0) res[1][19]=a0;
  if (res[1]!=0) res[1][20]=a0;
  if (res[1]!=0) res[1][21]=a2;
  if (res[1]!=0) res[1][22]=a2;
  if (res[1]!=0) res[1][23]=a0;
  if (res[1]!=0) res[1][24]=a0;
  if (res[1]!=0) res[1][25]=a2;
  if (res[1]!=0) res[1][26]=a2;
  if (res[1]!=0) res[1][27]=a0;
  if (res[1]!=0) res[1][28]=a0;
  if (res[1]!=0) res[1][29]=a2;
  if (res[1]!=0) res[1][30]=a2;
  if (res[1]!=0) res[1][31]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_constr_h_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
