/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[8] = {3, 3, 0, 0, 0, 2, 0, 1};
static const casadi_int casadi_s4[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s5[23] = {3, 8, 0, 2, 3, 5, 6, 8, 9, 11, 12, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[3] = {3, 0, 0};

/* GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z:(i0[3],i1[3],i2[8],i3[],i4[],i5[3])->(o0[3],o1[3x3,2nz],o2[3x3,3nz],o3[3x8,12nz],o4[3x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=3.;
  a4=arg[5]? arg[5][0] : 0;
  a5=arg[5]? arg[5][1] : 0;
  a6=(a4-a5);
  a6=(a3*a6);
  a7=arg[5]? arg[5][2] : 0;
  a8=(a5-a7);
  a6=(a6/a8);
  a8=(a4-a5);
  a8=casadi_sq(a8);
  a8=(a3*a8);
  a9=(a5-a7);
  a9=casadi_sq(a9);
  a8=(a8/a9);
  a6=(a6+a8);
  a8=(a4-a5);
  a9=casadi_sq(a8);
  a8=(a8*a9);
  a9=(a5-a7);
  a10=casadi_sq(a9);
  a9=(a9*a10);
  a8=(a8/a9);
  a6=(a6+a8);
  a8=1.;
  a6=(a6+a8);
  a2=(a2*a6);
  a9=arg[2]? arg[2][0] : 0;
  a10=(a2*a9);
  a11=cos(a1);
  a12=(a4-a5);
  a12=(a3*a12);
  a13=(a5-a7);
  a12=(a12/a13);
  a13=6.;
  a14=(a4-a5);
  a14=casadi_sq(a14);
  a13=(a13*a14);
  a14=(a5-a7);
  a14=casadi_sq(a14);
  a13=(a13/a14);
  a12=(a12+a13);
  a13=(a4-a5);
  a14=casadi_sq(a13);
  a13=(a13*a14);
  a13=(a3*a13);
  a14=(a5-a7);
  a15=casadi_sq(a14);
  a14=(a14*a15);
  a13=(a13/a14);
  a12=(a12+a13);
  a11=(a11*a12);
  a13=arg[2]? arg[2][2] : 0;
  a14=(a11*a13);
  a10=(a10-a14);
  a14=cos(a1);
  a15=(a4-a5);
  a15=casadi_sq(a15);
  a15=(a3*a15);
  a16=(a5-a7);
  a16=casadi_sq(a16);
  a15=(a15/a16);
  a16=(a4-a5);
  a17=casadi_sq(a16);
  a16=(a16*a17);
  a3=(a3*a16);
  a16=(a5-a7);
  a17=casadi_sq(a16);
  a16=(a16*a17);
  a3=(a3/a16);
  a15=(a15+a3);
  a14=(a14*a15);
  a3=arg[2]? arg[2][4] : 0;
  a16=(a14*a3);
  a10=(a10+a16);
  a16=cos(a1);
  a4=(a4-a5);
  a17=casadi_sq(a4);
  a4=(a4*a17);
  a5=(a5-a7);
  a7=casadi_sq(a5);
  a5=(a5*a7);
  a4=(a4/a5);
  a16=(a16*a4);
  a5=arg[2]? arg[2][6] : 0;
  a7=(a16*a5);
  a10=(a10-a7);
  a0=(a0-a10);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a10=sin(a1);
  a10=(a10*a6);
  a7=(a10*a9);
  a17=sin(a1);
  a17=(a17*a12);
  a18=(a17*a13);
  a7=(a7-a18);
  a18=sin(a1);
  a18=(a18*a15);
  a19=(a18*a3);
  a7=(a7+a19);
  a19=sin(a1);
  a19=(a19*a4);
  a20=(a19*a5);
  a7=(a7-a20);
  a0=(a0-a7);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a7=arg[2]? arg[2][1] : 0;
  a7=(a6*a7);
  a20=arg[2]? arg[2][3] : 0;
  a20=(a12*a20);
  a7=(a7-a20);
  a20=arg[2]? arg[2][5] : 0;
  a20=(a15*a20);
  a7=(a7+a20);
  a20=arg[2]? arg[2][7] : 0;
  a20=(a4*a20);
  a7=(a7-a20);
  a0=(a0-a7);
  if (res[0]!=0) res[0][2]=a0;
  a0=sin(a1);
  a0=(a12*a0);
  a0=(a13*a0);
  a7=sin(a1);
  a7=(a6*a7);
  a7=(a9*a7);
  a0=(a0-a7);
  a7=sin(a1);
  a7=(a15*a7);
  a7=(a3*a7);
  a0=(a0-a7);
  a7=sin(a1);
  a7=(a4*a7);
  a7=(a5*a7);
  a0=(a0+a7);
  a0=(-a0);
  if (res[1]!=0) res[1][0]=a0;
  a0=cos(a1);
  a0=(a6*a0);
  a9=(a9*a0);
  a0=cos(a1);
  a0=(a12*a0);
  a13=(a13*a0);
  a9=(a9-a13);
  a13=cos(a1);
  a13=(a15*a13);
  a3=(a3*a13);
  a9=(a9+a3);
  a1=cos(a1);
  a1=(a4*a1);
  a5=(a5*a1);
  a9=(a9-a5);
  a9=(-a9);
  if (res[1]!=0) res[1][1]=a9;
  if (res[2]!=0) res[2][0]=a8;
  if (res[2]!=0) res[2][1]=a8;
  if (res[2]!=0) res[2][2]=a8;
  a2=(-a2);
  if (res[3]!=0) res[3][0]=a2;
  a10=(-a10);
  if (res[3]!=0) res[3][1]=a10;
  a6=(-a6);
  if (res[3]!=0) res[3][2]=a6;
  if (res[3]!=0) res[3][3]=a11;
  if (res[3]!=0) res[3][4]=a17;
  if (res[3]!=0) res[3][5]=a12;
  a14=(-a14);
  if (res[3]!=0) res[3][6]=a14;
  a18=(-a18);
  if (res[3]!=0) res[3][7]=a18;
  a15=(-a15);
  if (res[3]!=0) res[3][8]=a15;
  if (res[3]!=0) res[3][9]=a16;
  if (res[3]!=0) res[3][10]=a19;
  if (res[3]!=0) res[3][11]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_impl_dae_fun_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
