/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s5[49] = {11, 11, 0, 4, 8, 12, 16, 20, 24, 28, 32, 33, 34, 35, 0, 2, 4, 6, 1, 3, 5, 7, 0, 2, 4, 6, 1, 3, 5, 7, 0, 2, 4, 6, 1, 3, 5, 7, 0, 2, 4, 6, 1, 3, 5, 7, 8, 9, 10};
static const casadi_int casadi_s6[14] = {0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess:(i0[3],i1[8],i2[],i3[3])->(o0,o1[11],o2[11x11,35nz],o3[],o4[0x11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a6, a7, a8, a9;
  a0=10.;
  a1=arg[0]? arg[0][0] : 0;
  a2=(a0*a1);
  a3=(a2*a1);
  a4=arg[0]? arg[0][1] : 0;
  a5=(a0*a4);
  a6=(a5*a4);
  a3=(a3+a6);
  a6=1.0000000000000000e-02;
  a7=arg[0]? arg[0][2] : 0;
  a8=(a6*a7);
  a9=(a8*a7);
  a3=(a3+a9);
  a9=1.4285714285714285e-01;
  a10=arg[1]? arg[1][0] : 0;
  a11=(a9*a10);
  a12=(a11*a10);
  a13=arg[1]? arg[1][1] : 0;
  a14=(a9*a13);
  a15=(a14*a13);
  a12=(a12+a15);
  a15=7.1428571428571425e-02;
  a16=arg[1]? arg[1][2] : 0;
  a17=(a15*a16);
  a18=(a17*a10);
  a19=arg[1]? arg[1][3] : 0;
  a20=(a15*a19);
  a21=(a20*a13);
  a18=(a18+a21);
  a12=(a12+a18);
  a18=2.8571428571428571e-02;
  a21=arg[1]? arg[1][4] : 0;
  a22=(a18*a21);
  a23=(a22*a10);
  a24=arg[1]? arg[1][5] : 0;
  a25=(a18*a24);
  a26=(a25*a13);
  a23=(a23+a26);
  a12=(a12+a23);
  a23=7.1428571428571426e-03;
  a26=arg[1]? arg[1][6] : 0;
  a27=(a23*a26);
  a28=(a27*a10);
  a29=arg[1]? arg[1][7] : 0;
  a30=(a23*a29);
  a31=(a30*a13);
  a28=(a28+a31);
  a12=(a12+a28);
  a28=(a15*a10);
  a31=(a28*a16);
  a32=(a15*a13);
  a33=(a32*a19);
  a31=(a31+a33);
  a12=(a12+a31);
  a31=8.5714285714285715e-02;
  a33=(a31*a16);
  a34=(a33*a16);
  a35=(a31*a19);
  a36=(a35*a19);
  a34=(a34+a36);
  a12=(a12+a34);
  a34=6.4285714285714279e-02;
  a36=(a34*a21);
  a37=(a36*a16);
  a38=(a34*a24);
  a39=(a38*a19);
  a37=(a37+a39);
  a12=(a12+a37);
  a37=(a18*a26);
  a39=(a37*a16);
  a40=(a18*a29);
  a41=(a40*a19);
  a39=(a39+a41);
  a12=(a12+a39);
  a39=(a18*a10);
  a41=(a39*a21);
  a42=(a18*a13);
  a43=(a42*a24);
  a41=(a41+a43);
  a12=(a12+a41);
  a41=(a34*a16);
  a43=(a41*a21);
  a44=(a34*a19);
  a45=(a44*a24);
  a43=(a43+a45);
  a12=(a12+a43);
  a43=(a31*a21);
  a45=(a43*a21);
  a46=(a31*a24);
  a47=(a46*a24);
  a45=(a45+a47);
  a12=(a12+a45);
  a45=(a15*a26);
  a47=(a45*a21);
  a48=(a15*a29);
  a49=(a48*a24);
  a47=(a47+a49);
  a12=(a12+a47);
  a47=(a23*a10);
  a49=(a47*a26);
  a50=(a23*a13);
  a51=(a50*a29);
  a49=(a49+a51);
  a12=(a12+a49);
  a49=(a18*a16);
  a51=(a49*a26);
  a52=(a18*a19);
  a53=(a52*a29);
  a51=(a51+a53);
  a12=(a12+a51);
  a51=(a15*a21);
  a53=(a51*a26);
  a54=(a15*a24);
  a55=(a54*a29);
  a53=(a53+a55);
  a12=(a12+a53);
  a53=(a9*a26);
  a55=(a53*a26);
  a56=(a9*a29);
  a57=(a56*a29);
  a55=(a55+a57);
  a12=(a12+a55);
  a3=(a3+a12);
  if (res[0]!=0) res[0][0]=a3;
  a3=(a23*a26);
  a12=(a18*a21);
  a3=(a3+a12);
  a12=(a15*a16);
  a3=(a3+a12);
  a3=(a3+a27);
  a3=(a3+a22);
  a3=(a3+a17);
  a3=(a3+a11);
  a11=(a9*a10);
  a3=(a3+a11);
  if (res[1]!=0) res[1][0]=a3;
  a3=(a23*a29);
  a11=(a18*a24);
  a3=(a3+a11);
  a11=(a15*a19);
  a3=(a3+a11);
  a3=(a3+a30);
  a3=(a3+a25);
  a3=(a3+a20);
  a3=(a3+a14);
  a14=(a9*a13);
  a3=(a3+a14);
  if (res[1]!=0) res[1][1]=a3;
  a3=(a18*a26);
  a14=(a34*a21);
  a3=(a3+a14);
  a3=(a3+a37);
  a3=(a3+a36);
  a3=(a3+a33);
  a33=(a31*a16);
  a3=(a3+a33);
  a3=(a3+a28);
  a28=(a15*a10);
  a3=(a3+a28);
  if (res[1]!=0) res[1][2]=a3;
  a3=(a18*a29);
  a28=(a34*a24);
  a3=(a3+a28);
  a3=(a3+a40);
  a3=(a3+a38);
  a3=(a3+a35);
  a35=(a31*a19);
  a3=(a3+a35);
  a3=(a3+a32);
  a32=(a15*a13);
  a3=(a3+a32);
  if (res[1]!=0) res[1][3]=a3;
  a3=(a15*a26);
  a3=(a3+a45);
  a3=(a3+a43);
  a43=(a31*a21);
  a3=(a3+a43);
  a3=(a3+a41);
  a3=(a3+a39);
  a39=(a34*a16);
  a3=(a3+a39);
  a39=(a18*a10);
  a3=(a3+a39);
  if (res[1]!=0) res[1][4]=a3;
  a3=(a15*a29);
  a3=(a3+a48);
  a3=(a3+a46);
  a31=(a31*a24);
  a3=(a3+a31);
  a3=(a3+a44);
  a3=(a3+a42);
  a34=(a34*a19);
  a3=(a3+a34);
  a34=(a18*a13);
  a3=(a3+a34);
  if (res[1]!=0) res[1][5]=a3;
  a26=(a9*a26);
  a53=(a53+a26);
  a53=(a53+a51);
  a53=(a53+a49);
  a53=(a53+a47);
  a21=(a15*a21);
  a53=(a53+a21);
  a16=(a18*a16);
  a53=(a53+a16);
  a10=(a23*a10);
  a53=(a53+a10);
  if (res[1]!=0) res[1][6]=a53;
  a29=(a9*a29);
  a56=(a56+a29);
  a56=(a56+a54);
  a56=(a56+a52);
  a56=(a56+a50);
  a15=(a15*a24);
  a56=(a56+a15);
  a18=(a18*a19);
  a56=(a56+a18);
  a23=(a23*a13);
  a56=(a56+a23);
  if (res[1]!=0) res[1][7]=a56;
  a1=(a0*a1);
  a2=(a2+a1);
  if (res[1]!=0) res[1][8]=a2;
  a0=(a0*a4);
  a5=(a5+a0);
  if (res[1]!=0) res[1][9]=a5;
  a6=(a6*a7);
  a8=(a8+a6);
  if (res[1]!=0) res[1][10]=a8;
  a8=2.8571428571428570e-01;
  if (res[2]!=0) res[2][0]=a8;
  if (res[2]!=0) res[2][1]=a9;
  a6=5.7142857142857141e-02;
  if (res[2]!=0) res[2][2]=a6;
  a7=1.4285714285714285e-02;
  if (res[2]!=0) res[2][3]=a7;
  if (res[2]!=0) res[2][4]=a8;
  if (res[2]!=0) res[2][5]=a9;
  if (res[2]!=0) res[2][6]=a6;
  if (res[2]!=0) res[2][7]=a7;
  if (res[2]!=0) res[2][8]=a9;
  a5=1.7142857142857143e-01;
  if (res[2]!=0) res[2][9]=a5;
  a0=1.2857142857142856e-01;
  if (res[2]!=0) res[2][10]=a0;
  if (res[2]!=0) res[2][11]=a6;
  if (res[2]!=0) res[2][12]=a9;
  if (res[2]!=0) res[2][13]=a5;
  if (res[2]!=0) res[2][14]=a0;
  if (res[2]!=0) res[2][15]=a6;
  if (res[2]!=0) res[2][16]=a6;
  if (res[2]!=0) res[2][17]=a0;
  if (res[2]!=0) res[2][18]=a5;
  if (res[2]!=0) res[2][19]=a9;
  if (res[2]!=0) res[2][20]=a6;
  if (res[2]!=0) res[2][21]=a0;
  if (res[2]!=0) res[2][22]=a5;
  if (res[2]!=0) res[2][23]=a9;
  if (res[2]!=0) res[2][24]=a7;
  if (res[2]!=0) res[2][25]=a6;
  if (res[2]!=0) res[2][26]=a9;
  if (res[2]!=0) res[2][27]=a8;
  if (res[2]!=0) res[2][28]=a7;
  if (res[2]!=0) res[2][29]=a6;
  if (res[2]!=0) res[2][30]=a9;
  if (res[2]!=0) res[2][31]=a8;
  a8=20.;
  if (res[2]!=0) res[2][32]=a8;
  if (res[2]!=0) res[2][33]=a8;
  a8=2.0000000000000000e-02;
  if (res[2]!=0) res[2][34]=a8;
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s2;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
