/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s5[87] = {11, 11, 0, 8, 16, 24, 32, 40, 48, 56, 64, 67, 70, 73, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 8, 9, 10, 8, 9, 10};
static const casadi_int casadi_s6[14] = {0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* GemCarModel_Bspline_cost_ext_cost_fun_jac_hess:(i0[3],i1[8],i2[],i3[3])->(o0,o1[11],o2[11x11,73nz],o3[],o4[0x11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a8, a9;
  a0=10.;
  a1=arg[0]? arg[0][0] : 0;
  a2=(a0*a1);
  a3=(a2*a1);
  a4=arg[0]? arg[0][1] : 0;
  a5=(a0*a4);
  a6=(a5*a4);
  a3=(a3+a6);
  a6=1.0000000000000000e-02;
  a7=arg[0]? arg[0][2] : 0;
  a8=(a6*a7);
  a9=(a8*a7);
  a3=(a3+a9);
  a9=casadi_sq(a3);
  a10=1.4285714285714285e-01;
  a11=arg[1]? arg[1][0] : 0;
  a12=casadi_sq(a11);
  a13=arg[1]? arg[1][1] : 0;
  a14=casadi_sq(a13);
  a12=(a12+a14);
  a12=(a10*a12);
  a14=casadi_sq(a12);
  a15=7.1428571428571425e-02;
  a16=arg[1]? arg[1][2] : 0;
  a17=(a16*a11);
  a18=arg[1]? arg[1][3] : 0;
  a19=(a18*a13);
  a17=(a17+a19);
  a17=(a15*a17);
  a19=casadi_sq(a17);
  a14=(a14+a19);
  a19=2.8571428571428571e-02;
  a20=arg[1]? arg[1][4] : 0;
  a21=(a20*a11);
  a22=arg[1]? arg[1][5] : 0;
  a23=(a22*a13);
  a21=(a21+a23);
  a21=(a19*a21);
  a23=casadi_sq(a21);
  a14=(a14+a23);
  a23=7.1428571428571426e-03;
  a24=arg[1]? arg[1][6] : 0;
  a25=(a24*a11);
  a26=arg[1]? arg[1][7] : 0;
  a27=(a26*a13);
  a25=(a25+a27);
  a25=(a23*a25);
  a27=casadi_sq(a25);
  a14=(a14+a27);
  a27=(a11*a16);
  a28=(a13*a18);
  a27=(a27+a28);
  a27=(a15*a27);
  a28=casadi_sq(a27);
  a14=(a14+a28);
  a28=8.5714285714285715e-02;
  a29=casadi_sq(a16);
  a30=casadi_sq(a18);
  a29=(a29+a30);
  a29=(a28*a29);
  a30=casadi_sq(a29);
  a14=(a14+a30);
  a30=6.4285714285714279e-02;
  a31=(a20*a16);
  a32=(a22*a18);
  a31=(a31+a32);
  a31=(a30*a31);
  a32=casadi_sq(a31);
  a14=(a14+a32);
  a32=(a24*a16);
  a33=(a26*a18);
  a32=(a32+a33);
  a32=(a19*a32);
  a33=casadi_sq(a32);
  a14=(a14+a33);
  a33=(a11*a20);
  a34=(a13*a22);
  a33=(a33+a34);
  a33=(a19*a33);
  a34=casadi_sq(a33);
  a14=(a14+a34);
  a34=(a16*a20);
  a35=(a18*a22);
  a34=(a34+a35);
  a34=(a30*a34);
  a35=casadi_sq(a34);
  a14=(a14+a35);
  a35=casadi_sq(a20);
  a36=casadi_sq(a22);
  a35=(a35+a36);
  a35=(a28*a35);
  a36=casadi_sq(a35);
  a14=(a14+a36);
  a36=(a24*a20);
  a37=(a26*a22);
  a36=(a36+a37);
  a36=(a15*a36);
  a37=casadi_sq(a36);
  a14=(a14+a37);
  a37=(a11*a24);
  a38=(a13*a26);
  a37=(a37+a38);
  a37=(a23*a37);
  a38=casadi_sq(a37);
  a14=(a14+a38);
  a38=(a16*a24);
  a39=(a18*a26);
  a38=(a38+a39);
  a38=(a19*a38);
  a39=casadi_sq(a38);
  a14=(a14+a39);
  a39=(a20*a24);
  a40=(a22*a26);
  a39=(a39+a40);
  a39=(a15*a39);
  a40=casadi_sq(a39);
  a14=(a14+a40);
  a40=casadi_sq(a24);
  a41=casadi_sq(a26);
  a40=(a40+a41);
  a40=(a10*a40);
  a41=casadi_sq(a40);
  a14=(a14+a41);
  a9=(a9+a14);
  if (res[0]!=0) res[0][0]=a9;
  a37=(a37+a37);
  a37=(a23*a37);
  a9=(a24*a37);
  a33=(a33+a33);
  a33=(a19*a33);
  a14=(a20*a33);
  a9=(a9+a14);
  a27=(a27+a27);
  a27=(a15*a27);
  a14=(a16*a27);
  a9=(a9+a14);
  a25=(a25+a25);
  a25=(a23*a25);
  a14=(a24*a25);
  a9=(a9+a14);
  a21=(a21+a21);
  a21=(a19*a21);
  a14=(a20*a21);
  a9=(a9+a14);
  a17=(a17+a17);
  a17=(a15*a17);
  a14=(a16*a17);
  a9=(a9+a14);
  a14=(a11+a11);
  a12=(a12+a12);
  a12=(a10*a12);
  a41=(a14*a12);
  a9=(a9+a41);
  if (res[1]!=0) res[1][0]=a9;
  a9=(a26*a37);
  a41=(a22*a33);
  a9=(a9+a41);
  a41=(a18*a27);
  a9=(a9+a41);
  a41=(a26*a25);
  a9=(a9+a41);
  a41=(a22*a21);
  a9=(a9+a41);
  a41=(a18*a17);
  a9=(a9+a41);
  a41=(a13+a13);
  a42=(a41*a12);
  a9=(a9+a42);
  if (res[1]!=0) res[1][1]=a9;
  a38=(a38+a38);
  a38=(a19*a38);
  a9=(a24*a38);
  a34=(a34+a34);
  a34=(a30*a34);
  a42=(a20*a34);
  a9=(a9+a42);
  a32=(a32+a32);
  a32=(a19*a32);
  a42=(a24*a32);
  a9=(a9+a42);
  a31=(a31+a31);
  a31=(a30*a31);
  a42=(a20*a31);
  a9=(a9+a42);
  a42=(a16+a16);
  a29=(a29+a29);
  a29=(a28*a29);
  a43=(a42*a29);
  a9=(a9+a43);
  a43=(a11*a27);
  a9=(a9+a43);
  a43=(a11*a17);
  a9=(a9+a43);
  if (res[1]!=0) res[1][2]=a9;
  a9=(a26*a38);
  a43=(a22*a34);
  a9=(a9+a43);
  a43=(a26*a32);
  a9=(a9+a43);
  a43=(a22*a31);
  a9=(a9+a43);
  a43=(a18+a18);
  a44=(a43*a29);
  a9=(a9+a44);
  a44=(a13*a27);
  a9=(a9+a44);
  a44=(a13*a17);
  a9=(a9+a44);
  if (res[1]!=0) res[1][3]=a9;
  a39=(a39+a39);
  a39=(a15*a39);
  a9=(a24*a39);
  a36=(a36+a36);
  a36=(a15*a36);
  a44=(a24*a36);
  a9=(a9+a44);
  a44=(a20+a20);
  a35=(a35+a35);
  a35=(a28*a35);
  a45=(a44*a35);
  a9=(a9+a45);
  a45=(a16*a34);
  a9=(a9+a45);
  a45=(a11*a33);
  a9=(a9+a45);
  a45=(a16*a31);
  a9=(a9+a45);
  a45=(a11*a21);
  a9=(a9+a45);
  if (res[1]!=0) res[1][4]=a9;
  a9=(a26*a39);
  a45=(a26*a36);
  a9=(a9+a45);
  a45=(a22+a22);
  a46=(a45*a35);
  a9=(a9+a46);
  a46=(a18*a34);
  a9=(a9+a46);
  a46=(a13*a33);
  a9=(a9+a46);
  a46=(a18*a31);
  a9=(a9+a46);
  a46=(a13*a21);
  a9=(a9+a46);
  if (res[1]!=0) res[1][5]=a9;
  a9=(a24+a24);
  a40=(a40+a40);
  a40=(a10*a40);
  a46=(a9*a40);
  a47=(a20*a39);
  a46=(a46+a47);
  a47=(a16*a38);
  a46=(a46+a47);
  a47=(a11*a37);
  a46=(a46+a47);
  a47=(a20*a36);
  a46=(a46+a47);
  a47=(a16*a32);
  a46=(a46+a47);
  a47=(a11*a25);
  a46=(a46+a47);
  if (res[1]!=0) res[1][6]=a46;
  a46=(a26+a26);
  a47=(a46*a40);
  a48=(a22*a39);
  a47=(a47+a48);
  a48=(a18*a38);
  a47=(a47+a48);
  a48=(a13*a37);
  a47=(a47+a48);
  a48=(a22*a36);
  a47=(a47+a48);
  a48=(a18*a32);
  a47=(a47+a48);
  a48=(a13*a25);
  a47=(a47+a48);
  if (res[1]!=0) res[1][7]=a47;
  a3=(a3+a3);
  a47=(a2*a3);
  a48=(a1*a3);
  a48=(a0*a48);
  a47=(a47+a48);
  if (res[1]!=0) res[1][8]=a47;
  a47=(a5*a3);
  a48=(a4*a3);
  a48=(a0*a48);
  a47=(a47+a48);
  if (res[1]!=0) res[1][9]=a47;
  a47=(a8*a3);
  a48=(a7*a3);
  a48=(a6*a48);
  a47=(a47+a48);
  if (res[1]!=0) res[1][10]=a47;
  a47=(a23*a24);
  a47=(a47+a47);
  a47=(a23*a47);
  a47=(a24*a47);
  a48=(a19*a20);
  a48=(a48+a48);
  a48=(a19*a48);
  a48=(a20*a48);
  a47=(a47+a48);
  a48=(a15*a16);
  a48=(a48+a48);
  a48=(a15*a48);
  a48=(a16*a48);
  a47=(a47+a48);
  a48=(a23*a24);
  a48=(a48+a48);
  a48=(a23*a48);
  a48=(a24*a48);
  a47=(a47+a48);
  a48=(a19*a20);
  a48=(a48+a48);
  a48=(a19*a48);
  a48=(a20*a48);
  a47=(a47+a48);
  a48=(a15*a16);
  a48=(a48+a48);
  a48=(a15*a48);
  a48=(a16*a48);
  a47=(a47+a48);
  a48=2.;
  a49=(a48*a12);
  a50=(a11+a11);
  a50=(a10*a50);
  a50=(a50+a50);
  a50=(a10*a50);
  a50=(a14*a50);
  a49=(a49+a50);
  a47=(a47+a49);
  if (res[2]!=0) res[2][0]=a47;
  a47=(a23*a26);
  a47=(a47+a47);
  a47=(a23*a47);
  a49=(a24*a47);
  a50=(a19*a22);
  a50=(a50+a50);
  a50=(a19*a50);
  a51=(a20*a50);
  a49=(a49+a51);
  a51=(a15*a18);
  a51=(a51+a51);
  a51=(a15*a51);
  a52=(a16*a51);
  a49=(a49+a52);
  a52=(a23*a26);
  a52=(a52+a52);
  a52=(a23*a52);
  a53=(a24*a52);
  a49=(a49+a53);
  a53=(a19*a22);
  a53=(a53+a53);
  a53=(a19*a53);
  a54=(a20*a53);
  a49=(a49+a54);
  a54=(a15*a18);
  a54=(a54+a54);
  a54=(a15*a54);
  a55=(a16*a54);
  a49=(a49+a55);
  a55=(a13+a13);
  a55=(a10*a55);
  a55=(a55+a55);
  a55=(a10*a55);
  a14=(a14*a55);
  a49=(a49+a14);
  if (res[2]!=0) res[2][1]=a49;
  a14=(a15*a11);
  a14=(a14+a14);
  a14=(a15*a14);
  a56=(a16*a14);
  a56=(a27+a56);
  a57=(a15*a11);
  a57=(a57+a57);
  a57=(a15*a57);
  a58=(a16*a57);
  a58=(a17+a58);
  a56=(a56+a58);
  if (res[2]!=0) res[2][2]=a56;
  a58=(a15*a13);
  a58=(a58+a58);
  a58=(a15*a58);
  a59=(a16*a58);
  a60=(a15*a13);
  a60=(a60+a60);
  a60=(a15*a60);
  a61=(a16*a60);
  a59=(a59+a61);
  if (res[2]!=0) res[2][3]=a59;
  a61=(a19*a11);
  a61=(a61+a61);
  a61=(a19*a61);
  a62=(a20*a61);
  a62=(a33+a62);
  a63=(a19*a11);
  a63=(a63+a63);
  a63=(a19*a63);
  a64=(a20*a63);
  a64=(a21+a64);
  a62=(a62+a64);
  if (res[2]!=0) res[2][4]=a62;
  a64=(a19*a13);
  a64=(a64+a64);
  a64=(a19*a64);
  a65=(a20*a64);
  a66=(a19*a13);
  a66=(a66+a66);
  a66=(a19*a66);
  a67=(a20*a66);
  a65=(a65+a67);
  if (res[2]!=0) res[2][5]=a65;
  a67=(a23*a11);
  a67=(a67+a67);
  a67=(a23*a67);
  a68=(a24*a67);
  a68=(a37+a68);
  a69=(a23*a11);
  a69=(a69+a69);
  a69=(a23*a69);
  a70=(a24*a69);
  a70=(a25+a70);
  a68=(a68+a70);
  if (res[2]!=0) res[2][6]=a68;
  a70=(a23*a13);
  a70=(a70+a70);
  a70=(a23*a70);
  a71=(a24*a70);
  a72=(a23*a13);
  a72=(a72+a72);
  a23=(a23*a72);
  a72=(a24*a23);
  a71=(a71+a72);
  if (res[2]!=0) res[2][7]=a71;
  if (res[2]!=0) res[2][8]=a49;
  a47=(a26*a47);
  a50=(a22*a50);
  a47=(a47+a50);
  a51=(a18*a51);
  a47=(a47+a51);
  a52=(a26*a52);
  a47=(a47+a52);
  a53=(a22*a53);
  a47=(a47+a53);
  a54=(a18*a54);
  a47=(a47+a54);
  a12=(a48*a12);
  a41=(a41*a55);
  a12=(a12+a41);
  a47=(a47+a12);
  if (res[2]!=0) res[2][9]=a47;
  a47=(a18*a14);
  a12=(a18*a57);
  a47=(a47+a12);
  if (res[2]!=0) res[2][10]=a47;
  a12=(a18*a58);
  a27=(a27+a12);
  a12=(a18*a60);
  a17=(a17+a12);
  a27=(a27+a17);
  if (res[2]!=0) res[2][11]=a27;
  a17=(a22*a61);
  a12=(a22*a63);
  a17=(a17+a12);
  if (res[2]!=0) res[2][12]=a17;
  a12=(a22*a64);
  a33=(a33+a12);
  a12=(a22*a66);
  a21=(a21+a12);
  a33=(a33+a21);
  if (res[2]!=0) res[2][13]=a33;
  a21=(a26*a67);
  a12=(a26*a69);
  a21=(a21+a12);
  if (res[2]!=0) res[2][14]=a21;
  a12=(a26*a70);
  a37=(a37+a12);
  a12=(a26*a23);
  a25=(a25+a12);
  a37=(a37+a25);
  if (res[2]!=0) res[2][15]=a37;
  if (res[2]!=0) res[2][16]=a56;
  if (res[2]!=0) res[2][17]=a47;
  a47=(a19*a24);
  a47=(a47+a47);
  a47=(a19*a47);
  a47=(a24*a47);
  a56=(a30*a20);
  a56=(a56+a56);
  a56=(a30*a56);
  a56=(a20*a56);
  a47=(a47+a56);
  a56=(a19*a24);
  a56=(a56+a56);
  a56=(a19*a56);
  a56=(a24*a56);
  a47=(a47+a56);
  a56=(a30*a20);
  a56=(a56+a56);
  a56=(a30*a56);
  a56=(a20*a56);
  a47=(a47+a56);
  a56=(a48*a29);
  a25=(a16+a16);
  a25=(a28*a25);
  a25=(a25+a25);
  a25=(a28*a25);
  a25=(a42*a25);
  a56=(a56+a25);
  a47=(a47+a56);
  a14=(a11*a14);
  a47=(a47+a14);
  a57=(a11*a57);
  a47=(a47+a57);
  if (res[2]!=0) res[2][18]=a47;
  a47=(a19*a26);
  a47=(a47+a47);
  a47=(a19*a47);
  a57=(a24*a47);
  a14=(a30*a22);
  a14=(a14+a14);
  a14=(a30*a14);
  a56=(a20*a14);
  a57=(a57+a56);
  a56=(a19*a26);
  a56=(a56+a56);
  a56=(a19*a56);
  a25=(a24*a56);
  a57=(a57+a25);
  a25=(a30*a22);
  a25=(a25+a25);
  a25=(a30*a25);
  a12=(a20*a25);
  a57=(a57+a12);
  a12=(a18+a18);
  a12=(a28*a12);
  a12=(a12+a12);
  a12=(a28*a12);
  a42=(a42*a12);
  a57=(a57+a42);
  a42=(a11*a58);
  a57=(a57+a42);
  a42=(a11*a60);
  a57=(a57+a42);
  if (res[2]!=0) res[2][19]=a57;
  a42=(a30*a16);
  a42=(a42+a42);
  a42=(a30*a42);
  a41=(a20*a42);
  a41=(a34+a41);
  a55=(a30*a16);
  a55=(a55+a55);
  a55=(a30*a55);
  a54=(a20*a55);
  a54=(a31+a54);
  a41=(a41+a54);
  if (res[2]!=0) res[2][20]=a41;
  a54=(a30*a18);
  a54=(a54+a54);
  a54=(a30*a54);
  a53=(a20*a54);
  a52=(a30*a18);
  a52=(a52+a52);
  a30=(a30*a52);
  a52=(a20*a30);
  a53=(a53+a52);
  if (res[2]!=0) res[2][21]=a53;
  a52=(a19*a16);
  a52=(a52+a52);
  a52=(a19*a52);
  a51=(a24*a52);
  a51=(a38+a51);
  a50=(a19*a16);
  a50=(a50+a50);
  a50=(a19*a50);
  a49=(a24*a50);
  a49=(a32+a49);
  a51=(a51+a49);
  if (res[2]!=0) res[2][22]=a51;
  a49=(a19*a18);
  a49=(a49+a49);
  a49=(a19*a49);
  a72=(a24*a49);
  a73=(a19*a18);
  a73=(a73+a73);
  a19=(a19*a73);
  a73=(a24*a19);
  a72=(a72+a73);
  if (res[2]!=0) res[2][23]=a72;
  if (res[2]!=0) res[2][24]=a59;
  if (res[2]!=0) res[2][25]=a27;
  if (res[2]!=0) res[2][26]=a57;
  a47=(a26*a47);
  a14=(a22*a14);
  a47=(a47+a14);
  a56=(a26*a56);
  a47=(a47+a56);
  a25=(a22*a25);
  a47=(a47+a25);
  a29=(a48*a29);
  a43=(a43*a12);
  a29=(a29+a43);
  a47=(a47+a29);
  a58=(a13*a58);
  a47=(a47+a58);
  a60=(a13*a60);
  a47=(a47+a60);
  if (res[2]!=0) res[2][27]=a47;
  a47=(a22*a42);
  a60=(a22*a55);
  a47=(a47+a60);
  if (res[2]!=0) res[2][28]=a47;
  a60=(a22*a54);
  a34=(a34+a60);
  a60=(a22*a30);
  a31=(a31+a60);
  a34=(a34+a31);
  if (res[2]!=0) res[2][29]=a34;
  a31=(a26*a52);
  a60=(a26*a50);
  a31=(a31+a60);
  if (res[2]!=0) res[2][30]=a31;
  a60=(a26*a49);
  a38=(a38+a60);
  a60=(a26*a19);
  a32=(a32+a60);
  a38=(a38+a32);
  if (res[2]!=0) res[2][31]=a38;
  if (res[2]!=0) res[2][32]=a62;
  if (res[2]!=0) res[2][33]=a17;
  if (res[2]!=0) res[2][34]=a41;
  if (res[2]!=0) res[2][35]=a47;
  a47=(a15*a24);
  a47=(a47+a47);
  a47=(a15*a47);
  a47=(a24*a47);
  a41=(a15*a24);
  a41=(a41+a41);
  a41=(a15*a41);
  a41=(a24*a41);
  a47=(a47+a41);
  a41=(a48*a35);
  a17=(a20+a20);
  a17=(a28*a17);
  a17=(a17+a17);
  a17=(a28*a17);
  a17=(a44*a17);
  a41=(a41+a17);
  a47=(a47+a41);
  a42=(a16*a42);
  a47=(a47+a42);
  a61=(a11*a61);
  a47=(a47+a61);
  a55=(a16*a55);
  a47=(a47+a55);
  a63=(a11*a63);
  a47=(a47+a63);
  if (res[2]!=0) res[2][36]=a47;
  a47=(a15*a26);
  a47=(a47+a47);
  a47=(a15*a47);
  a63=(a24*a47);
  a55=(a15*a26);
  a55=(a55+a55);
  a55=(a15*a55);
  a61=(a24*a55);
  a63=(a63+a61);
  a61=(a22+a22);
  a61=(a28*a61);
  a61=(a61+a61);
  a28=(a28*a61);
  a44=(a44*a28);
  a63=(a63+a44);
  a44=(a16*a54);
  a63=(a63+a44);
  a44=(a11*a64);
  a63=(a63+a44);
  a44=(a16*a30);
  a63=(a63+a44);
  a44=(a11*a66);
  a63=(a63+a44);
  if (res[2]!=0) res[2][37]=a63;
  a44=(a15*a20);
  a44=(a44+a44);
  a44=(a15*a44);
  a61=(a24*a44);
  a61=(a39+a61);
  a42=(a15*a20);
  a42=(a42+a42);
  a42=(a15*a42);
  a41=(a24*a42);
  a41=(a36+a41);
  a61=(a61+a41);
  if (res[2]!=0) res[2][38]=a61;
  a41=(a15*a22);
  a41=(a41+a41);
  a41=(a15*a41);
  a17=(a24*a41);
  a62=(a15*a22);
  a62=(a62+a62);
  a15=(a15*a62);
  a62=(a24*a15);
  a17=(a17+a62);
  if (res[2]!=0) res[2][39]=a17;
  if (res[2]!=0) res[2][40]=a65;
  if (res[2]!=0) res[2][41]=a33;
  if (res[2]!=0) res[2][42]=a53;
  if (res[2]!=0) res[2][43]=a34;
  if (res[2]!=0) res[2][44]=a63;
  a47=(a26*a47);
  a55=(a26*a55);
  a47=(a47+a55);
  a35=(a48*a35);
  a45=(a45*a28);
  a35=(a35+a45);
  a47=(a47+a35);
  a54=(a18*a54);
  a47=(a47+a54);
  a64=(a13*a64);
  a47=(a47+a64);
  a30=(a18*a30);
  a47=(a47+a30);
  a66=(a13*a66);
  a47=(a47+a66);
  if (res[2]!=0) res[2][45]=a47;
  a47=(a26*a44);
  a66=(a26*a42);
  a47=(a47+a66);
  if (res[2]!=0) res[2][46]=a47;
  a66=(a26*a41);
  a39=(a39+a66);
  a66=(a26*a15);
  a36=(a36+a66);
  a39=(a39+a36);
  if (res[2]!=0) res[2][47]=a39;
  if (res[2]!=0) res[2][48]=a68;
  if (res[2]!=0) res[2][49]=a21;
  if (res[2]!=0) res[2][50]=a51;
  if (res[2]!=0) res[2][51]=a31;
  if (res[2]!=0) res[2][52]=a61;
  if (res[2]!=0) res[2][53]=a47;
  a47=(a48*a40);
  a24=(a24+a24);
  a24=(a10*a24);
  a24=(a24+a24);
  a24=(a10*a24);
  a24=(a9*a24);
  a47=(a47+a24);
  a44=(a20*a44);
  a47=(a47+a44);
  a52=(a16*a52);
  a47=(a47+a52);
  a67=(a11*a67);
  a47=(a47+a67);
  a42=(a20*a42);
  a47=(a47+a42);
  a50=(a16*a50);
  a47=(a47+a50);
  a69=(a11*a69);
  a47=(a47+a69);
  if (res[2]!=0) res[2][54]=a47;
  a26=(a26+a26);
  a26=(a10*a26);
  a26=(a26+a26);
  a10=(a10*a26);
  a9=(a9*a10);
  a26=(a20*a41);
  a9=(a9+a26);
  a26=(a16*a49);
  a9=(a9+a26);
  a26=(a11*a70);
  a9=(a9+a26);
  a20=(a20*a15);
  a9=(a9+a20);
  a16=(a16*a19);
  a9=(a9+a16);
  a11=(a11*a23);
  a9=(a9+a11);
  if (res[2]!=0) res[2][55]=a9;
  if (res[2]!=0) res[2][56]=a71;
  if (res[2]!=0) res[2][57]=a37;
  if (res[2]!=0) res[2][58]=a72;
  if (res[2]!=0) res[2][59]=a38;
  if (res[2]!=0) res[2][60]=a17;
  if (res[2]!=0) res[2][61]=a39;
  if (res[2]!=0) res[2][62]=a9;
  a48=(a48*a40);
  a46=(a46*a10);
  a48=(a48+a46);
  a41=(a22*a41);
  a48=(a48+a41);
  a49=(a18*a49);
  a48=(a48+a49);
  a70=(a13*a70);
  a48=(a48+a70);
  a22=(a22*a15);
  a48=(a48+a22);
  a18=(a18*a19);
  a48=(a48+a18);
  a13=(a13*a23);
  a48=(a48+a13);
  if (res[2]!=0) res[2][63]=a48;
  a48=(a0*a3);
  a13=(a0*a1);
  a13=(a13+a2);
  a13=(a13+a13);
  a23=(a2*a13);
  a48=(a48+a23);
  a13=(a1*a13);
  a13=(a3+a13);
  a13=(a0*a13);
  a48=(a48+a13);
  if (res[2]!=0) res[2][64]=a48;
  a48=(a0*a4);
  a48=(a48+a5);
  a48=(a48+a48);
  a13=(a2*a48);
  a23=(a1*a48);
  a23=(a0*a23);
  a13=(a13+a23);
  if (res[2]!=0) res[2][65]=a13;
  a23=(a6*a7);
  a23=(a23+a8);
  a23=(a23+a23);
  a2=(a2*a23);
  a1=(a1*a23);
  a1=(a0*a1);
  a2=(a2+a1);
  if (res[2]!=0) res[2][66]=a2;
  if (res[2]!=0) res[2][67]=a13;
  a13=(a0*a3);
  a1=(a5*a48);
  a13=(a13+a1);
  a48=(a4*a48);
  a48=(a3+a48);
  a48=(a0*a48);
  a13=(a13+a48);
  if (res[2]!=0) res[2][68]=a13;
  a5=(a5*a23);
  a4=(a4*a23);
  a0=(a0*a4);
  a5=(a5+a0);
  if (res[2]!=0) res[2][69]=a5;
  if (res[2]!=0) res[2][70]=a2;
  if (res[2]!=0) res[2][71]=a5;
  a5=(a6*a3);
  a8=(a8*a23);
  a5=(a5+a8);
  a7=(a7*a23);
  a3=(a3+a7);
  a6=(a6*a3);
  a5=(a5+a6);
  if (res[2]!=0) res[2][72]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s2;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GemCarModel_Bspline_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
